### ISSUE TITLE
[Suggestion] Remove width size lock

### ISSUE THREAD

**Issue by Caliel666** [Brod8362/d4m#19]
it was fine before but with the new additions of 0.3.2 it causes for things to not be visible at all times, it also affects maximizing (on kde)
![ezgif-5-ab98e28bcd](https://user-images.githubusercontent.com/38433434/181636798-6499f0af-e8e2-4ea6-a37b-901f84daea09.gif)

as you can see, having both the previews and file size visible at the same time is difficult, at least on my theme/font size

**Comment by Caliel666** [comment]
it's not a big issue for me personally but it could cause more issues if someone has things bigger (maybe system wide scale)

**Comment by Brod8362** [comment]
Sure, will do in next release

**Comment by Brod8362** [comment]
Fixed in v0.3.3.
