### ISSUE TITLE
[unstable] problems with mod load order

### ISSUE THREAD

**Issue by Caliel666** [Brod8362/d4m#22]
the load order feature works just fine, the problem i'm facing occurs in 2 occasions:

1- when hitting the refresh button
2- when launching d4m
3- using on TUI*

this causes the mods order to reset graphically, it doesn't change the order in the config until you actually move a mod, then it will update with the incorrect order

*on TUI the issue is even worse, it has some text issue where it keeps duplicating the names as you move them

disclaimer: using my own build, which could mean that they issue doesn't happen on your machine and won't happen on release

**Comment by Caliel666** [comment]
i think this issue happens because d4m doesn't check for current load order in the config file, overwriting it every time it updates the load order, also means that "refresh" doesn't check for it either

**Comment by Brod8362** [comment]
Fixed in v0.3.3? I was never able to reproduce this. If it happens again please reopen the issue.
