### ISSUE TITLE
Add mod load order

### ISSUE THREAD

**Issue by Caliel666** [Brod8362/d4m#5]
you can change mod load order with the parameter `priority = ` on DML's config.toml

ex:

```priority = ["High Refresh Rate", "DivaBackup", "Disable Watermarks"]```
highest < lowest

on the GUI this could be achieved by drag and drop and/or right clicking the numbers on the left side and editing the number
on TUI it could be done by adding a edit mode when managing mods and use arrows up and down or something like that to change a mod position

video example on how DMM does it:

![ezgif-1-df748c4190](https://user-images.githubusercontent.com/38433434/180922547-c15c85f9-aa85-4700-a3d5-3c5b4bcd006c.gif)

**Comment by Brod8362** [comment]
Thanks for the video and idea, didn't know this was even an option.

Probably not going to happen in 0.3.0, but maybe expect this around 0.3.1/0.3.2.

**Comment by Brod8362** [comment]
Tentatively planning for 0.3.3

**Comment by Brod8362** [comment]
Added in v0.3.3.
