### ISSUE TITLE
Add button to edit mod config file

### ISSUE THREAD

**Issue by Caliel666** [Brod8362/d4m#6]
self explanatory, some mods, like high refresh rate, have user configurations in the config file inside the mod folder

now this should be very low prio as you can just open the game folder via d4m and easily get to that file, but it would be nice to have a button or right click (context menu perhaps?) the mod to open it's specific config file, could open with the system's default text editor, not sure how to deal with that on TUI tbh

**Comment by ScoreUnder** [comment]
> not sure how to deal with that on TUI tbh

I think @Brod8362 already knows this so I may not be adding much but many systems set an `EDITOR` or `VISUAL` environment variable which points to a default text editor to use, which gets used in tools like `crontab` and `sudoedit`. Otherwise, `nano` is a sensible fallback.

**Comment by Brod8362** [comment]
Yes, I was planning on using `$EDITOR` for TUI. That's easy, nothing to worry about.

The part I'm less sure about is how to manage this in the GUI version, *especially* on windows. I'll need to look into if there's some kind of xdg-open equivalent for windows.

**Comment by ScoreUnder** [comment]
There's this windows-only function: https://docs.python.org/3/library/os.html#os.startfile

**Comment by Brod8362** [comment]
Implemented in [v0.3.1](https://github.com/Brod8362/d4m/releases/tag/v0.3.1)
